-- ============================================================
-- Chạy file này trong Supabase Dashboard > SQL Editor
-- để tạo bảng activity_logs mà Edge Function sync-activity
-- sẽ ghi dữ liệu vào.
-- ============================================================

create table if not exists public.activity_logs (
    id                bigint generated by default as identity primary key,
    device_id         text not null,
    process_name      text not null,
    window_title      text not null,
    duration_seconds  bigint not null,
    start_time        bigint not null,
    end_time          bigint not null,
    created_at        timestamptz not null default now()
);

-- Bắt buộc phải có UNIQUE này để Edge Function upsert
-- (onConflict: "device_id,start_time") hoạt động đúng,
-- tránh tạo bản ghi trùng khi agent gửi lại record đã gửi
-- thành công trước đó nhưng chưa kịp đánh dấu synced cục bộ.
create unique index if not exists activity_logs_device_start_uidx
    on public.activity_logs (device_id, start_time);

create index if not exists activity_logs_device_time_idx
    on public.activity_logs (device_id, start_time desc);

-- ------------------------------------------------------------
-- Row Level Security (RLS)
-- ------------------------------------------------------------
-- Kiến trúc mới: client (.exe) KHÔNG còn gọi thẳng vào
-- /rest/v1/activity_logs bằng publishable key nữa, mà gọi
-- vào Edge Function "sync-activity". Function đó dùng
-- service_role key (chỉ tồn tại trên server Supabase) để
-- ghi dữ liệu, và service_role LUÔN bỏ qua RLS.
--
-- Vì vậy bảng này KHÔNG cần (và không nên có) bất kỳ policy
-- nào cho anon/authenticated/public. Bật RLS mà không tạo
-- policy nào = mặc định từ chối hoàn toàn mọi truy cập từ
-- client trực tiếp, kể cả khi publishable key bị lộ.
-- ------------------------------------------------------------

alter table public.activity_logs enable row level security;

-- Dọn sạch các policy cũ (nếu có) từ các lần thử trước,
-- để đảm bảo không còn policy nào cho anon/public.
drop policy if exists "allow insert" on public.activity_logs;
drop policy if exists "allow anon insert only" on public.activity_logs;
drop policy if exists "allow anon update for upsert" on public.activity_logs;
drop policy if exists "allow insert for sync agent" on public.activity_logs;
drop policy if exists "allow update for sync agent" on public.activity_logs;

-- Không tạo policy nào khác ở đây. Bảng chỉ ghi được qua
-- Edge Function (service_role).
