-- ============================================================
-- Chạy file này trong Supabase Dashboard > SQL Editor
-- để tạo/cập nhật bảng activity_logs.
-- ============================================================

create table if not exists public.activity_logs (
    id                bigint generated by default as identity primary key,
    user_id           uuid references auth.users(id) on delete cascade,
    device_id         text not null,
    process_name      text not null,
    window_title      text not null,
    duration_seconds  bigint not null,
    start_time        bigint not null,
    end_time          bigint not null,
    created_at        timestamptz not null default now()
);

-- Nếu bảng đã tồn tại từ trước (phiên bản chưa có user_id),
-- chạy dòng này để thêm cột (an toàn, bỏ qua nếu đã có):
alter table public.activity_logs
    add column if not exists user_id uuid references auth.users(id) on delete cascade;

-- Xóa unique index cũ (chỉ theo device_id, start_time) nếu có,
-- vì giờ cần phân biệt theo cả user_id (nhiều người có thể
-- dùng device_id trùng tên máy khác nhau).
drop index if exists public.activity_logs_device_start_uidx;

-- Bắt buộc phải có UNIQUE này để Edge Function upsert
-- (onConflict: "user_id,device_id,start_time") hoạt động đúng,
-- tránh tạo bản ghi trùng khi agent gửi lại record đã gửi
-- thành công trước đó nhưng chưa kịp đánh dấu synced cục bộ.
create unique index if not exists activity_logs_user_device_start_uidx
    on public.activity_logs (user_id, device_id, start_time);

create index if not exists activity_logs_user_time_idx
    on public.activity_logs (user_id, start_time desc);

-- ------------------------------------------------------------
-- Row Level Security (RLS)
-- ------------------------------------------------------------
-- Client (.exe) KHÔNG gọi thẳng vào /rest/v1/activity_logs,
-- mà gọi qua Edge Function "sync-activity". Function đó xác
-- thực access_token thật của user rồi dùng service_role key
-- (chỉ tồn tại trên server) để ghi dữ liệu - service_role LUÔN
-- bỏ qua RLS.
--
-- RLS ở đây chỉ dùng để: cho phép CHÍNH CHỦ tài khoản tự đọc
-- lại dữ liệu của mình (qua publishable key + access_token
-- thật của họ, phục vụ dashboard/xem báo cáo sau này), và
-- CHẶN HOÀN TOÀN mọi truy cập khác (kể cả giữa các user với
-- nhau, hay từ publishable key không có access_token).
-- ------------------------------------------------------------

alter table public.activity_logs enable row level security;

-- Dọn sạch các policy cũ từ các lần thử trước.
drop policy if exists "allow insert" on public.activity_logs;
drop policy if exists "allow anon insert only" on public.activity_logs;
drop policy if exists "allow anon update for upsert" on public.activity_logs;
drop policy if exists "allow insert for sync agent" on public.activity_logs;
drop policy if exists "allow update for sync agent" on public.activity_logs;
drop policy if exists "user can read own data" on public.activity_logs;

create policy "user can read own data"
    on public.activity_logs
    for select
    to authenticated
    using (auth.uid() = user_id);

-- Không tạo policy insert/update/delete nào cho client.
-- Chỉ Edge Function (service_role) mới ghi được.

-- ------------------------------------------------------------
-- View tổng hợp: tổng thời gian dùng mỗi app theo từng ngày,
-- gộp lại từ các record nhỏ bị chia theo window title.
-- ------------------------------------------------------------

create or replace view public.activity_daily_totals as
select
    user_id,
    device_id,
    process_name,
    (to_timestamp(start_time) at time zone 'utc')::date as day,
    sum(duration_seconds) as total_seconds
from public.activity_logs
group by
    user_id,
    device_id,
    process_name,
    (to_timestamp(start_time) at time zone 'utc')::date
order by day desc, total_seconds desc;

-- View kế thừa RLS của bảng gốc theo user hiện tại nếu được
-- tạo với security_invoker (PostgreSQL 15+). Nếu Supabase
-- project của bạn hỗ trợ, bật thêm dòng dưới để đảm bảo view
-- luôn tôn trọng RLS thay vì chạy bằng quyền người tạo view:
-- alter view public.activity_daily_totals set (security_invoker = true);

revoke all on public.activity_daily_totals from anon, public;
grant select on public.activity_daily_totals to authenticated;

-- Ví dụ query xem tổng thời gian hôm nay của CHÍNH BẠN,
-- chạy qua REST API với access_token thật của bạn:
-- select * from activity_daily_totals where day = current_date;
