-- ============================================================
-- 004_parent_links.sql
--
-- Cho phép 1 tài khoản "phụ huynh" xem hoạt động của 1 tài
-- khoản "con" - CHỈ SAU KHI tài khoản con chủ động đồng ý
-- (status chuyển từ 'pending' sang 'approved'). Con có thể
-- thu hồi quyền này bất kỳ lúc nào (status -> 'revoked').
--
-- Đây là mô hình MINH BẠCH, có sự đồng thuận - khác hoàn toàn
-- với giám sát ẩn: không có đường nào để phụ huynh xem được
-- dữ liệu của 1 tài khoản khác nếu tài khoản đó chưa approve.
--
-- Chạy trong Supabase Dashboard > SQL Editor, sau khi đã có
-- supabase_schema.sql và migrations/002, 003.
-- ============================================================

create table if not exists public.parent_links (
    id              bigint generated by default as identity primary key,
    parent_user_id  uuid not null default auth.uid() references auth.users(id) on delete cascade,
    child_user_id   uuid not null references auth.users(id) on delete cascade,
    status          text not null default 'pending'
                        check (status in ('pending', 'approved', 'revoked')),
    created_at      timestamptz not null default now(),
    approved_at     timestamptz,
    revoked_at      timestamptz,

    unique (parent_user_id, child_user_id),
    check (parent_user_id <> child_user_id)
);

create index if not exists parent_links_child_idx  on public.parent_links (child_user_id, status);
create index if not exists parent_links_parent_idx on public.parent_links (parent_user_id, status);

alter table public.parent_links enable row level security;

drop policy if exists "parent can see own links"        on public.parent_links;
drop policy if exists "child can see own links"          on public.parent_links;
drop policy if exists "parent can create pending invite" on public.parent_links;
drop policy if exists "child can approve or revoke"      on public.parent_links;
drop policy if exists "parent can revoke own invite"     on public.parent_links;

-- Mỗi bên chỉ thấy các dòng liên quan tới chính mình (là cha
-- hoặc là con trong dòng đó) - không ai thấy được liên kết
-- của người khác.
create policy "parent can see own links"
    on public.parent_links for select
    to authenticated
    using (auth.uid() = parent_user_id);

create policy "child can see own links"
    on public.parent_links for select
    to authenticated
    using (auth.uid() = child_user_id);

-- Phụ huynh tạo lời mời mới - LUÔN ở trạng thái 'pending', và
-- chỉ được tạo với parent_user_id = chính mình (không thể mạo
-- danh phụ huynh khác, và không thể tự tạo dòng 'approved').
create policy "parent can create pending invite"
    on public.parent_links for insert
    to authenticated
    with check (
        auth.uid() = parent_user_id
        and status = 'pending'
    );

-- Con là người DUY NHẤT được chuyển pending -> approved, và
-- cũng là người có thể tự revoke bất kỳ lúc nào.
create policy "child can approve or revoke"
    on public.parent_links for update
    to authenticated
    using (auth.uid() = child_user_id)
    with check (auth.uid() = child_user_id);

-- Phụ huynh cũng được phép tự huỷ lời mời do mình gửi (revoke
-- từ phía mình), nhưng KHÔNG được tự approve lời mời của mình.
create policy "parent can revoke own invite"
    on public.parent_links for update
    to authenticated
    using (auth.uid() = parent_user_id)
    with check (
        auth.uid() = parent_user_id
        and status = 'revoked'
    );

-- Tự động điền approved_at/revoked_at khi status đổi, để phía
-- client chỉ cần PATCH {"status": "approved"} hoặc
-- {"status": "revoked"}, không cần tự tính timestamp.
create or replace function public.parent_links_set_timestamps()
returns trigger
language plpgsql
as $$
begin
    if new.status = 'approved' and old.status is distinct from 'approved' then
        new.approved_at := now();
    end if;

    if new.status = 'revoked' and old.status is distinct from 'revoked' then
        new.revoked_at := now();
    end if;

    return new;
end;
$$;

drop trigger if exists trg_parent_links_set_timestamps on public.parent_links;

create trigger trg_parent_links_set_timestamps
    before update on public.parent_links
    for each row
    execute function public.parent_links_set_timestamps();


-- ------------------------------------------------------------
-- RPC: tra email -> user_id để tạo lời mời, mà không lộ toàn bộ
-- bảng auth.users cho client (Supabase không cho SELECT trực
-- tiếp auth.users từ client).
-- ------------------------------------------------------------
create or replace function public.find_user_id_by_email(target_email text)
returns uuid
language sql
security definer
set search_path = public, auth
as $$
    select id from auth.users where email = target_email limit 1;
$$;

revoke all on function public.find_user_id_by_email(text) from public;
grant execute on function public.find_user_id_by_email(text) to authenticated;


-- ------------------------------------------------------------
-- RPC: liệt kê link kèm email (client không được SELECT trực
-- tiếp auth.users, nên phải qua RPC security definer, tự lọc
-- theo auth.uid() bên trong - không nhận tham số user_id từ
-- client để không ai giả mạo xem hộ người khác).
-- ------------------------------------------------------------

create or replace function public.parent_links_for_parent()
returns table (
    id serial,
    child_user_id uuid,
    child_email text,
    status text,
    created_at timestamptz,
    approved_at timestamptz
)
language sql
security definer
set search_path = public, auth
as $$
    select pl.id, pl.child_user_id, u.email, pl.status, pl.created_at, pl.approved_at
    from public.parent_links pl
    join auth.users u on u.id = pl.child_user_id
    where pl.parent_user_id = auth.uid()
    order by pl.created_at desc;
$$;

revoke all on function public.parent_links_for_parent() from public;
grant execute on function public.parent_links_for_parent() to authenticated;


create or replace function public.parent_links_for_child()
returns table (
    id serial,
    parent_user_id uuid,
    parent_email text,
    status text,
    created_at timestamptz,
    approved_at timestamptz
)
language sql
security definer
set search_path = public, auth
as $$
    select pl.id, pl.parent_user_id, u.email, pl.status, pl.created_at, pl.approved_at
    from public.parent_links pl
    join auth.users u on u.id = pl.parent_user_id
    where pl.child_user_id = auth.uid()
    order by pl.created_at desc;
$$;

revoke all on function public.parent_links_for_child() from public;
grant execute on function public.parent_links_for_child() to authenticated;


-- ------------------------------------------------------------
-- app_limits: giới hạn thời gian / chặn app, do phụ huynh đặt
-- cho 1 tài khoản con cụ thể. Con đọc bảng này để tự kiểm tra
-- và tự chặn app quá giờ (agent không bao giờ bị phụ huynh
-- điều khiển trực tiếp - chỉ đọc "luật" rồi tự áp dụng).
-- ------------------------------------------------------------

create table if not exists public.app_limits (
    id              bigint generated by default as identity primary key,
    child_user_id   uuid not null references auth.users(id) on delete cascade,
    set_by          uuid not null default auth.uid() references auth.users(id),
    process_name    text not null,
    daily_limit_sec integer,          -- null = không giới hạn thời gian (chỉ dùng blocked)
    blocked         boolean not null default false,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),

    unique (child_user_id, process_name)
);

create index if not exists app_limits_child_idx on public.app_limits (child_user_id);

create or replace function public.app_limits_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists trg_app_limits_touch_updated_at on public.app_limits;

create trigger trg_app_limits_touch_updated_at
    before update on public.app_limits
    for each row
    execute function public.app_limits_touch_updated_at();

alter table public.app_limits enable row level security;

drop policy if exists "child can read own limits"      on public.app_limits;
drop policy if exists "approved parent can read limits" on public.app_limits;
drop policy if exists "approved parent can set limits"  on public.app_limits;

-- Con luôn đọc được giới hạn của chính mình (để tự thực thi).
create policy "child can read own limits"
    on public.app_limits for select
    to authenticated
    using (auth.uid() = child_user_id);

-- Phụ huynh chỉ đọc/ghi được giới hạn của 1 tài khoản con NẾU
-- đã có dòng parent_links ở trạng thái 'approved' giữa 2 bên -
-- đây là chỗ enforce chính của toàn bộ mô hình đồng thuận.
create policy "approved parent can read limits"
    on public.app_limits for select
    to authenticated
    using (
        exists (
            select 1 from public.parent_links pl
            where pl.parent_user_id = auth.uid()
              and pl.child_user_id  = app_limits.child_user_id
              and pl.status = 'approved'
        )
    );

create policy "approved parent can set limits"
    on public.app_limits for all
    to authenticated
    using (
        exists (
            select 1 from public.parent_links pl
            where pl.parent_user_id = auth.uid()
              and pl.child_user_id  = app_limits.child_user_id
              and pl.status = 'approved'
        )
    )
    with check (
        set_by = auth.uid()
        and exists (
            select 1 from public.parent_links pl
            where pl.parent_user_id = auth.uid()
              and pl.child_user_id  = app_limits.child_user_id
              and pl.status = 'approved'
        )
    );

-- ------------------------------------------------------------
-- Cho phép phụ huynh đã được approve đọc activity_daily_totals
-- của con (bảng/view này được tạo trong supabase_schema.sql
-- gốc - cần thêm policy dưới đây vào bảng activity_logs, vì
-- policy hiện tại chỉ cho user đọc dữ liệu CỦA CHÍNH MÌNH).
-- ------------------------------------------------------------

drop policy if exists "approved parent can read child activity" on public.activity_logs;

create policy "approved parent can read child activity"
    on public.activity_logs for select
    to authenticated
    using (
        exists (
            select 1 from public.parent_links pl
            where pl.parent_user_id = auth.uid()
              and pl.child_user_id  = activity_logs.user_id
              and pl.status = 'approved'
        )
    );
