-- ============================================================
-- app_releases: bảng công khai (chỉ đọc) để JustInTime tự kiểm
-- tra phiên bản mới. Không cần đăng nhập - RLS chỉ cho phép
-- role "anon" SELECT, không ai (kể cả user đã đăng nhập) được
-- ghi qua client; chỉ bạn tự thêm dòng mới trong Supabase
-- Dashboard mỗi khi phát hành bản mới.
--
-- Chạy trong Supabase Dashboard > SQL Editor.
-- ============================================================

create table if not exists public.app_releases (
    id            bigint generated by default as identity primary key,
    version       text not null,               -- vd '1.1.0' (khớp APP_VERSION trong config.h)
    download_url  text not null,                -- link tải bản cài đặt (.exe) mới nhất
    notes         text not null default '',     -- release notes ngắn, hiển thị trong thông báo
    published_at  timestamptz not null default now()
);

alter table public.app_releases enable row level security;

drop policy if exists "anyone can read releases" on public.app_releases;

create policy "anyone can read releases"
    on public.app_releases
    for select
    to anon, authenticated
    using (true);

-- Không tạo policy insert/update/delete cho anon/authenticated
-- => chỉ có thể ghi bằng service_role (trong Supabase Dashboard,
-- hoặc script chạy với service_role key), client không bao giờ
-- ghi được vào bảng này.

-- Thêm 1 dòng mẫu để test ngay (sửa version/URL cho khớp bản
-- hiện tại của bạn, hoặc xoá dòng này nếu chưa muốn công bố gì):
-- insert into public.app_releases (version, download_url, notes)
-- values ('1.0.0', 'https://example.com/downloads/JustInTime-Setup-1.0.0.exe', 'First release.');
