-- ============================================================
-- device_messages: cho phép các thiết bị CỦA CÙNG MỘT NGƯỜI
-- DÙNG gửi tin nhắn / dữ liệu cho nhau qua device_id, thông
-- qua Supabase làm relay (client không bao giờ kết nối trực
-- tiếp máy-tới-máy — giữ đúng kiến trúc "client chỉ nói chuyện
-- với Supabase" mà activity sync đã dùng).
--
-- Chạy file này trong Supabase Dashboard > SQL Editor, sau khi
-- đã có supabase_schema.sql (activity_logs, activity_daily_totals).
-- ============================================================

create table if not exists public.device_messages (
    id                bigint generated by default as identity primary key,
    user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
    sender_device_id  text not null,
    target_device_id  text not null,
    kind              text not null check (kind in ('message', 'data')),
    payload           text not null,
    created_at        timestamptz not null default now(),
    read_at           timestamptz
);

create index if not exists device_messages_inbox_idx
    on public.device_messages (user_id, target_device_id, created_at desc);

alter table public.device_messages enable row level security;

drop policy if exists "user can read own messages" on public.device_messages;
drop policy if exists "user can send own messages" on public.device_messages;
drop policy if exists "user can mark own messages read" on public.device_messages;

-- Chỉ đọc được tin nhắn/dữ liệu thuộc về tài khoản của chính
-- mình (bao gồm cả những gì chính mình đã gửi, để có thể xem
-- lại lịch sử nếu cần).
create policy "user can read own messages"
    on public.device_messages
    for select
    to authenticated
    using (auth.uid() = user_id);

-- Chỉ được tạo bản ghi gắn với chính user_id của mình. user_id
-- có default = auth.uid(), nên client (Go dashboard) không cần
-- và không nên tự gửi user_id lên — Supabase tự điền.
create policy "user can send own messages"
    on public.device_messages
    for insert
    to authenticated
    with check (auth.uid() = user_id);

-- Cho phép đánh dấu đã đọc (chỉ với bản ghi của chính mình).
create policy "user can mark own messages read"
    on public.device_messages
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- (Tuỳ chọn) dọn tin nhắn cũ hơn 30 ngày, chạy định kỳ nếu muốn:
-- delete from public.device_messages where created_at < now() - interval '30 days';
